version: '3.7'

services:
  nginx:
    build: ./.docker/nginx
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/hosts/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/var/www
      - ./.docker/nginx/logs:/var/log/nginx
  php:
    build: ./.docker/php
    volumes:
      - ./:/var/www
    restart: always
    links:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "6603:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
